import type { FormEvent } from "react";
import { DataView } from "../../components/DataView";
import type { KnowledgeBase, Member, OrganizationSummary, PermissionMatrix, Report, Source } from "../../app/domain-types";

type Quotas = { max_concurrent_analyses: number; daily_analysis_runs: number; max_document_size_mb: number; retention_days: number };
type Props = { organization: OrganizationSummary | null; members: Member[]; sources: Source[]; knowledgeBases: KnowledgeBase[]; reports: Report[]; permissions: PermissionMatrix | null; quotas: Quotas; setQuotas: (next: Quotas) => void; busy: boolean; onNavigate: (nav: string) => void; onUpdateOwner: (event: FormEvent) => void; onOwnerChange: (userId: string) => void; onUpdateQuotas: (event: FormEvent) => void };
export function ProjectManagementPage(p: Props) {
  const canManage = ["org_admin", "platform_admin"].includes(p.organization?.role || "");
  const resourceCards = [["成员", p.organization?.member_count ?? "—", "组织与审计", "管理成员 →"], ["数据源", p.organization?.data_source_count ?? p.sources.length, "数据源", "查看数据源 →"], ["知识库", p.organization?.knowledge_base_count ?? p.knowledgeBases.length, "知识库", "维护知识库 →"], ["报告", p.organization?.report_count ?? p.reports.length, "报告中心", "打开报告中心 →"]] as const;
  return <DataView kicker="WORKSPACE / PROJECT CONTROL" title="项目管理" copy="统一查看组织资源、成员权限和运行配额。">
    <section className="project-summary">{resourceCards.map(([label, count, nav, action]) => <article key={label}><span>{label}</span><strong>{count}</strong><button className="text-button" onClick={() => p.onNavigate(nav)}>{action}</button></article>)}</section>
    <section className="project-access"><div><p className="section-kicker">ORGANIZATION / {p.organization?.slug || "LOADING"}</p><h3>{p.organization?.name || "组织概览"}</h3><p>当前角色：{p.organization?.role || "—"}。资源统计和权限均来自组织接口。</p></div><div className="access-list"><span><b className="access-dot allowed" />成员与角色</span><span><b className="access-dot allowed" />数据源配置</span><span><b className="access-dot allowed" />知识库摄取</span><span><b className="access-dot allowed" />审计查看</span></div></section>
    <section className="project-management-grid"><form className="quota-form" onSubmit={p.onUpdateOwner}><div className="panel-heading"><div><p className="section-kicker">ORGANIZATION / OWNER</p><h3>企业负责人</h3></div><span className="panel-meta">仅组织管理员可修改</span></div><label>负责人<select value={p.organization?.owner_user_id || ""} disabled={!canManage || p.busy} onChange={(event) => p.onOwnerChange(event.target.value)}><option value="">请选择组织成员</option>{p.members.filter((member) => member.is_active).map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name} · {member.email}</option>)}</select></label><button className="primary-button" disabled={!canManage || p.busy}>保存负责人</button></form>
      <form className="quota-form" onSubmit={p.onUpdateQuotas}><div className="panel-heading"><div><p className="section-kicker">QUOTA / ORGANIZATION POLICY</p><h3>组织配额</h3></div><span className="panel-meta">保存前请确认影响范围</span></div>{([ ["分析并发数", "max_concurrent_analyses", 1, 100], ["每日分析次数", "daily_analysis_runs", 1, 100000], ["单文件大小（MB）", "max_document_size_mb", 1, 1024], ["数据保留天数", "retention_days", 1, 3650] ] as const).map(([label, key, min, max]) => <label key={key}>{label}<input type="number" min={min} max={max} value={p.quotas[key]} onChange={(event) => p.setQuotas({ ...p.quotas, [key]: Number(event.target.value) })} /></label>)}<button className="primary-button" disabled={p.busy}>保存配额</button></form>
      <section className="permission-panel"><div className="panel-heading"><div><p className="section-kicker">ACCESS / ROLE MATRIX</p><h3>权限矩阵</h3></div></div><div className="permission-table">{p.permissions && Object.entries(p.permissions.roles).map(([role, actions]) => <div className="permission-row" key={role}><strong>{role}</strong><span>{Object.entries(actions).filter(([, allowed]) => allowed).map(([action]) => action.replaceAll("_", " ")).join(" · ") || "仅查看授权资源"}</span></div>)}</div></section>
    </section>
  </DataView>;
}
