import type { FormEvent, Ref } from "react";
import type { Dashboard, DashboardFilters } from "../../app/types";
import { DashboardFilters as DashboardFiltersPanel } from "./DashboardFilters";
import { AnalysisPanel } from "../analysis/AnalysisPanel";
import type { AnalysisResult, KnowledgeBase, Source } from "../../app/domain-types";

type DashboardConfig = { dashboard_id: string; refresh_interval_seconds: number; visible_widgets: string[] };
type Props = { dashboard: Dashboard | null; dimensions: { factories: string[]; product_lines: string[]; suppliers: string[] }; filters: DashboardFilters; refreshing: boolean; config: DashboardConfig; canConfigure: boolean; onChangeFilters: (value: DashboardFilters) => void; onRefresh: () => void; onSaveConfig: (seconds: number) => void; onOpenAnalysis: (question?: string) => void; chartRef: Ref<HTMLDivElement>; factoryChartRef: Ref<HTMLDivElement>; supplierChartRef: Ref<HTMLDivElement>; question: string; setQuestion: (value: string) => void; events: string[]; result: AnalysisResult | null; busy: boolean; onSubmit: (event: FormEvent) => void; onDownloadReport: (id: string) => Promise<void>; sources: Source[]; knowledgeBases: KnowledgeBase[]; sourceId: string; knowledgeBaseId: string; setSourceId: (value: string) => void; setKnowledgeBaseId: (value: string) => void };
export function OperationsOverviewPage(p: Props) {
  const visible = new Set(p.config.visible_widgets.length ? p.config.visible_widgets : ["delivery", "production", "inventory", "quality", "fulfillment", "trend", "factories", "suppliers"]);
  const show = (key: string) => visible.has(key);
  return <><DashboardFiltersPanel value={p.filters} refreshing={p.refreshing} cacheStatus={p.dashboard?.cache_status} refreshedAt={p.dashboard?.refreshed_at} dimensions={p.dimensions} onChange={p.onChangeFilters} onRefresh={p.onRefresh} config={p.config} canConfigure={p.canConfigure} onSaveConfig={p.onSaveConfig} />
    <section className="hero-row"><div><p className="section-kicker">OPERATIONS / LIVE SNAPSHOT</p><h1>早上好，管理员。</h1><p className="hero-copy">这里是当前筛选范围内的供应链运行快照，指标来自已授权数据源的实时聚合。</p></div><div className="hero-stamp"><span>数据覆盖</span><strong>5</strong><small>个运营指标</small></div></section>
    <section className="metric-grid">{p.dashboard?.cards.filter((card) => show(card.label.includes("采购") ? "delivery" : card.label.includes("生产") ? "production" : card.label.includes("库存") ? "inventory" : card.label.includes("质量") ? "quality" : "fulfillment")).map((card) => <article className="metric" key={card.label}><div className="metric-label"><span className="metric-pip" />{card.label}</div><strong>{card.value}</strong><span className="metric-change">{card.change}<small>较上期</small></span></article>)}</section>
    {show("trend") && <section className="main-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p className="section-kicker">PERFORMANCE / 30 DAYS</p><h3>生产达成率趋势</h3></div><span className="panel-meta">目标线 90%</span></div><div ref={p.chartRef} className="chart-canvas" /></article><article className="panel risk-panel"><div className="panel-heading"><div><p className="section-kicker">ATTENTION REQUIRED</p><h3>待处置风险</h3></div><span className="risk-count">{String(p.dashboard?.anomalies?.length || 0).padStart(2, "0")}</span></div><div className="risk-list">{(p.dashboard?.anomalies || []).slice(0, 4).map((item, index) => <button className="risk-item risk-item-button" key={`${item.type}-${item.factory || index}`} onClick={() => p.onOpenAnalysis(String(item.analysis_question || "分析生产达成率偏低原因"))}><span className={`risk-mark ${item.rate !== undefined && item.rate < 80 ? "high" : "medium"}`}>!</span><div><strong>生产达成偏低</strong><p>{item.factory || "未分配工厂"} 当前 {Number(item.rate || 0).toFixed(1)}%</p></div><span>→</span></button>)}{!p.dashboard?.anomalies?.length && <p className="empty-state">当前筛选范围暂无异常</p>}</div><button className="text-button" onClick={() => p.onOpenAnalysis()}>查看全部风险 <span>→</span></button></article></section>}
    {(show("factories") || show("suppliers")) && <section className="main-grid" style={{ marginTop: 20 }}>{show("factories") && <article className="panel"><div className="panel-heading"><div><p className="section-kicker">RANKING / FACTORIES</p><h3>工厂生产达成排行</h3></div></div>{(p.dashboard?.rankings?.factories || []).length ? <div ref={p.factoryChartRef} className="ranking-chart" aria-label="工厂生产达成率排行图" /> : <p className="empty-state">暂无工厂排行数据</p>}</article>}{show("suppliers") && <article className="panel"><div className="panel-heading"><div><p className="section-kicker">RANKING / SUPPLIERS</p><h3>供应商交付排行</h3></div></div>{(p.dashboard?.rankings?.suppliers || []).length ? <div ref={p.supplierChartRef} className="ranking-chart" aria-label="供应商交付准时率排行图" /> : <p className="empty-state">暂无供应商排行数据</p>}</article>}</section>}
    <AnalysisPanel question={p.question} setQuestion={p.setQuestion} events={p.events} result={p.result} loading={p.busy} onSubmit={p.onSubmit} onDownloadReport={p.onDownloadReport} sources={p.sources} knowledgeBases={p.knowledgeBases} sourceId={p.sourceId} knowledgeBaseId={p.knowledgeBaseId} setSourceId={p.setSourceId} setKnowledgeBaseId={p.setKnowledgeBaseId} />
  </>;
}
