import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell } from "../../components/AppShell";
import { API_BASE, apiRequest } from "../../services/api";
import { readSseResponse, type SseEvent } from "../../services/sse";
import type { AnalysisResult, KnowledgeBase, Source } from "../../app/domain-types";
import { AnalysisPanel } from "./AnalysisPanel";

type Progress = { name: string; status: "pending" | "running" | "completed" | "failed"; detail?: string };
const stageNames: Record<string, string> = { router: "识别问题", rag: "检索口径", schema: "读取数据结构", sql_planner: "生成查询", sql_guard: "校验查询", query: "执行查询", insight: "整理结论", report: "生成报告" };
const initialProgress = Object.entries(stageNames).map(([id, name]) => ({ id, name, status: "pending" as const }));

export function AnalysisRoute() {
  const navigate = useNavigate();
  const [token, setToken] = useState(() => localStorage.getItem("supplymind_token") || "");
  const [sources, setSources] = useState<Source[]>([]); const [knowledgeBases, setKnowledgeBases] = useState<KnowledgeBase[]>([]);
  const [sourceId, setSourceId] = useState(""); const [knowledgeBaseId, setKnowledgeBaseId] = useState(""); const [question, setQuestion] = useState("");
  const [progress, setProgress] = useState<Progress[]>(initialProgress); const [result, setResult] = useState<AnalysisResult | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const api = useCallback(<T,>(path: string, init?: RequestInit) => apiRequest<T>(API_BASE, token, path, init, localStorage.getItem("supplymind_refresh") || undefined, (access, refresh) => { setToken(access); localStorage.setItem("supplymind_token", access); localStorage.setItem("supplymind_refresh", refresh); }), [token]);
  useEffect(() => { if (!token) { navigate("/"); return; } void Promise.all([api<Source[]>("/data-sources"), api<KnowledgeBase[]>("/knowledge-bases?page=1&page_size=100")]).then(([nextSources, nextKnowledge]) => { setSources(nextSources.filter((item) => item.status !== "disabled")); setKnowledgeBases(nextKnowledge); }).catch((cause) => setError(cause instanceof Error ? cause.message : "无法加载分析资源")); }, [api, navigate, token]);
  const update = (event: SseEvent) => { const step = String(event.data.step || ""); if (event.event === "step_started" && step) setProgress((items) => items.map((item) => item.name === stageNames[step] ? { ...item, status: "running", detail: String(event.data.message || "处理中") } : item)); if (event.event === "sql_draft") setProgress((items) => items.map((item) => item.name === stageNames.sql_planner ? { ...item, status: "completed", detail: "已生成 SQL 草案" } : item)); if (event.event === "tool_result") setProgress((items) => items.map((item) => item.name === stageNames.query ? { ...item, status: "completed", detail: `${String(event.data.row_count || 0)} 行数据` } : item)); if (event.event === "chart_ready") setProgress((items) => items.map((item) => item.name === stageNames.insight ? { ...item, status: "completed", detail: "图表已就绪" } : item)); if (event.event === "failed") { setError(String(event.data.message || "分析失败")); setProgress((items) => items.map((item) => item.status === "running" ? { ...item, status: "failed", detail: String(event.data.message || "分析失败") } : item)); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!sourceId || !knowledgeBaseId) return setError("请选择数据源和知识库。"); setBusy(true); setError(""); setResult(null); setProgress(initialProgress); try { const response = await fetch(`${API_BASE}/analyses/stream`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ data_source_id: sourceId, knowledge_base_id: knowledgeBaseId, question, conversation_id: crypto.randomUUID() }) }); if (!response.ok) throw new Error(`${(await response.json().catch(() => ({}))).detail || "分析请求失败"}（Trace ID: ${response.headers.get("x-trace-id") || "—"}）`); const raw = await readSseResponse(response, (events) => events.forEach(update)); const completed = raw.match(/event: completed\ndata: (.+)/)?.[1]; if (completed) setResult({ ...(JSON.parse(completed) as AnalysisResult), trace_id: response.headers.get("x-trace-id") || undefined }); } catch (cause) { setError(cause instanceof Error ? cause.message : "分析失败"); } finally { setBusy(false); } };
  return <AppShell nav="分析会话" items={["运营总览", "项目管理", "企业管理", "大屏配置", "分析会话", "数据源", "知识库", "报告中心", "组织与审计", "系统状态"]} busy={busy} onNavigate={(item) => navigate(({ "运营总览": "/overview", "项目管理": "/project", "企业管理": "/platform/organizations", "大屏配置": "/dashboard/configuration", "分析会话": "/analysis", "数据源": "/data-sources", "知识库": "/knowledge", "报告中心": "/reports", "组织与审计": "/audit", "系统状态": "/system-status" } as Record<string, string>)[item])} onRefresh={() => window.location.reload()} onLogout={() => { localStorage.clear(); navigate("/"); }}><AnalysisPanel question={question} setQuestion={setQuestion} loading={busy} onSubmit={submit} onDownloadReport={async () => undefined} sources={sources} knowledgeBases={knowledgeBases} sourceId={sourceId} knowledgeBaseId={knowledgeBaseId} setSourceId={setSourceId} setKnowledgeBaseId={setKnowledgeBaseId} result={result} events={[...progress.filter((item) => item.status !== "pending").map((item) => `${item.name} · ${item.detail || item.status}`), error].filter(Boolean)} /></AppShell>;
}
