import type { FormEvent } from "react";

type AnalysisResult = { sql?: string; result?: { rows?: Record<string, unknown>[]; insight?: string; chart?: Record<string, unknown>; citations?: Record<string, unknown>[]; report_id?: string }; report_id?: string };

type Props = { question: string; setQuestion: (value: string) => void; events: string[]; result: AnalysisResult | null; loading: boolean; onSubmit: (event: FormEvent) => void; onDownloadReport: (id: string) => Promise<void> };

export function AnalysisPanel({ question, setQuestion, events, result, loading, onSubmit, onDownloadReport }: Props) {
  const rows = result?.result?.rows || [];
  const citations = result?.result?.citations || [];
  return <section className="analyst-panel standalone"><div className="analyst-intro"><div className="analyst-icon">✦</div><div><p className="section-kicker">ANALYSIS ASSISTANT</p><h3>问一个供应链问题</h3><p>结果包含安全 SQL、图表、引用和报告。</p></div></div><form onSubmit={onSubmit} className="analyst-form"><input value={question} onChange={(event) => setQuestion(event.target.value)} aria-label="供应链问题" /><button className="primary-button" disabled={loading}>{loading ? "分析中..." : "开始分析"}<span>↗</span></button></form>{events.length > 0 && <div className="event-log" aria-live="polite">{events.map((event, index) => <p key={`${event}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span>{event}</p>)}</div>}{result && <div className="analysis-result"><div className="result-heading"><p className="section-kicker">TRACEABLE RESULT</p><strong>{result.result?.insight || "分析已完成"}</strong></div>{result.sql && <pre className="sql-preview"><code>{result.sql}</code></pre>}{rows.length > 0 && <div className="result-table-wrap"><table className="result-table"><thead><tr>{Object.keys(rows[0]).map((key) => <th key={key}>{key}</th>)}</tr></thead><tbody>{rows.slice(0, 50).map((row, index) => <tr key={index}>{Object.keys(rows[0]).map((key) => <td key={key}>{String(row[key] ?? "-")}</td>)}</tr>)}</tbody></table></div>}{result.result?.chart && <details className="result-detail"><summary>图表规格</summary><pre>{JSON.stringify(result.result.chart, null, 2)}</pre></details>}{citations.length > 0 && <details className="result-detail" open><summary>引用依据（{citations.length}）</summary>{citations.map((citation, index) => <p key={index}>{String(citation.filename || citation.document_id || "文档")} · {String(citation.location || citation.score || "已引用")}</p>)}</details>}{(result.report_id || result.result?.report_id) && <button className="secondary-button" onClick={() => void onDownloadReport(String(result.report_id || result.result?.report_id))}>下载 PDF 报告</button>}</div>}</section>;
}
