import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell } from "../../components/AppShell";
import { API_BASE, apiRequest } from "../../services/api";
import { readSseResponse, type SseEvent } from "../../services/sse";
import type { AgentStep, AnalysisResult, AnalysisRun, KnowledgeBase, Source } from "../../app/domain-types";
import { AnalysisPanel } from "./AnalysisPanel";
import { AnalysisHistory } from "./AnalysisHistory";
import { AnalysisRunDetail } from "./AnalysisRunDetail";
import { freshSnapshot, mergeAnalysisEvent } from "./analysis-stream";


export function AnalysisRoute() {
  const navigate = useNavigate();
  const [token, setToken] = useState(() => localStorage.getItem("supplymind_token") || "");
  const [sources, setSources] = useState<Source[]>([]); const [knowledgeBases, setKnowledgeBases] = useState<KnowledgeBase[]>([]);
  const [sourceId, setSourceId] = useState(""); const [knowledgeBaseId, setKnowledgeBaseId] = useState(""); const [question, setQuestion] = useState("");
  const [stream, setStream] = useState(freshSnapshot); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [runs, setRuns] = useState<AnalysisRun[]>([]); const [selectedRun, setSelectedRun] = useState<AnalysisRun | null>(null); const [steps, setSteps] = useState<AgentStep[]>([]);
  const api = useCallback(<T,>(path: string, init?: RequestInit) => apiRequest<T>(API_BASE, token, path, init, localStorage.getItem("supplymind_refresh") || undefined, (access, refresh) => { setToken(access); localStorage.setItem("supplymind_token", access); localStorage.setItem("supplymind_refresh", refresh); }), [token]);
  const refreshRuns = useCallback(() => api<AnalysisRun[]>("/analyses?page=1&page_size=10").then(setRuns), [api]);
  useEffect(() => { if (!token) { navigate("/"); return; } void Promise.all([api<Source[]>("/data-sources"), api<KnowledgeBase[]>("/knowledge-bases?page=1&page_size=100"), refreshRuns()]).then(([nextSources, nextKnowledge]) => { setSources(nextSources.filter((item) => item.status === "active")); setKnowledgeBases(nextKnowledge); }).catch((cause) => setError(cause instanceof Error ? cause.message : "无法加载分析资源")); }, [api, navigate, refreshRuns, token]);
  const openRun = useCallback(async (id: string) => { setBusy(true); try { const [run, nextSteps] = await Promise.all([api<AnalysisRun>(`/analyses/${id}`), api<AgentStep[]>(`/analyses/${id}/steps`)]); setSelectedRun(run); setSteps(nextSteps); setStream((current) => ({ ...current, runId: run.id, result: run.result ? { run_id: run.id, sql: run.sql, sql_draft: run.sql_draft, guard_error: run.guard_error, result: run.result } : null })); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法恢复分析运行"); } finally { setBusy(false); } }, [api]);
  const update = useCallback((event: SseEvent) => { setStream((current) => mergeAnalysisEvent(current, event)); if (event.event === "queued" && event.data.run_id) setSelectedRun({ id: String(event.data.run_id), question, status: "running", created_at: new Date().toISOString(), data_source_id: sourceId, knowledge_base_id: knowledgeBaseId }); if (["completed", "failed", "cancelled"].includes(event.event)) void refreshRuns(); }, [knowledgeBaseId, question, refreshRuns, sourceId]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!sourceId || !knowledgeBaseId) return setError("请选择数据源和知识库。"); setBusy(true); setError(""); setStream(freshSnapshot()); try { const response = await fetch(`${API_BASE}/analyses/stream`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ data_source_id: sourceId, knowledge_base_id: knowledgeBaseId, question, conversation_id: crypto.randomUUID() }) }); if (!response.ok) throw new Error(`${(await response.json().catch(() => ({}))).detail || "分析请求失败"}（Trace ID: ${response.headers.get("x-trace-id") || "-"}）`); await readSseResponse(response, (events) => events.forEach(update)); } catch (cause) { setError(cause instanceof Error ? cause.message : "分析失败"); } finally { setBusy(false); } };
  const cancel = (id: string) => void api(`/analyses/${id}/cancel`, { method: "POST" }).then(() => openRun(id)).then(refreshRuns).catch((cause) => setError(cause instanceof Error ? cause.message : "取消失败"));
  const retry = (id: string) => void fetch(`${API_BASE}/analyses/${id}/retry`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error("分析重试失败"); await readSseResponse(response, (events) => events.forEach(update)); }).then(refreshRuns).catch((cause) => setError(cause instanceof Error ? cause.message : "分析重试失败"));
  return <AppShell nav="分析会话" items={["运营总览", "项目管理", "企业管理", "大屏配置", "分析会话", "数据源", "知识库", "报告中心", "组织与审计", "系统状态"]} busy={busy} onNavigate={(item) => navigate(({ "运营总览": "/overview", "项目管理": "/project", "企业管理": "/platform/organizations", "大屏配置": "/dashboard/configuration", "分析会话": "/analysis", "数据源": "/data-sources", "知识库": "/knowledge", "报告中心": "/reports", "组织与审计": "/audit", "系统状态": "/system-status" } as Record<string, string>)[item])} onRefresh={() => void refreshRuns()} onLogout={() => { localStorage.clear(); navigate("/"); }}><AnalysisPanel question={question} setQuestion={setQuestion} loading={busy} onSubmit={submit} sources={sources} knowledgeBases={knowledgeBases} sourceId={sourceId} knowledgeBaseId={knowledgeBaseId} setSourceId={setSourceId} setKnowledgeBaseId={setKnowledgeBaseId} stages={stream.stages} citationCount={stream.citationCount} rowCount={stream.rowCount} chartReady={stream.chartReady} error={error || stream.error} result={stream.result} /><AnalysisHistory runs={runs} onOpen={(id) => void openRun(id)} />{selectedRun && <AnalysisRunDetail run={selectedRun} steps={steps} sources={sources} knowledgeBases={knowledgeBases} busy={busy} onClose={() => setSelectedRun(null)} onCancel={cancel} onRetry={retry} />}</AppShell>;
}
