import { FormEvent, useState } from "react";

export type DocumentTaskRow = { id: string; filename: string; status: string; is_archived?: boolean; category?: string; embedding_model?: string; embedding_dimension?: number; error_message?: string; ingestion_task_id?: string; knowledge_base_id?: string; duplicate?: boolean; metric_name?: string; metric_definition?: string; metric_formula?: string; metric_unit?: string; applicable_factories?: string[]; applicable_product_lines?: string[]; effective_from?: string };
type Metadata = { metric_name: string; metric_definition: string; metric_formula: string; metric_unit: string; applicable_factories: string[]; applicable_product_lines: string[]; effective_from: string | null };
type Props = { documents: DocumentTaskRow[]; knowledgeBaseId: string; organizationRole?: string; onSource: (document: DocumentTaskRow) => void; onRetry: (taskId: string) => void; onCancel: (taskId: string) => void; onArchive: (document: DocumentTaskRow) => void; onDelete: (document: DocumentTaskRow) => void; onReplace: (document: DocumentTaskRow, file: File) => Promise<void>; onMetadata: (document: DocumentTaskRow, metadata: Metadata) => Promise<void> };

function MetadataEditor({ document, onSave }: { document: DocumentTaskRow; onSave: (metadata: Metadata) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ metric_name: document.metric_name || "", metric_definition: document.metric_definition || "", metric_formula: document.metric_formula || "", metric_unit: document.metric_unit || "", applicable_factories: (document.applicable_factories || []).join(", "), applicable_product_lines: (document.applicable_product_lines || []).join(", "), effective_from: document.effective_from ? document.effective_from.slice(0, 10) : "" });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); try { await onSave({ ...form, applicable_factories: form.applicable_factories.split(",").map((item) => item.trim()).filter(Boolean), applicable_product_lines: form.applicable_product_lines.split(",").map((item) => item.trim()).filter(Boolean), effective_from: form.effective_from ? `${form.effective_from}T00:00:00Z` : null }); setOpen(false); } finally { setSaving(false); } }
  if (!open) return <button className="text-button" onClick={() => setOpen(true)}>编辑口径</button>;
  return <form className="metadata-editor" onSubmit={(event) => void submit(event)}><label>指标名称<input value={form.metric_name} onChange={(event) => setForm({ ...form, metric_name: event.target.value })} /></label><label>定义<textarea rows={2} value={form.metric_definition} onChange={(event) => setForm({ ...form, metric_definition: event.target.value })} /></label><label>公式<input value={form.metric_formula} onChange={(event) => setForm({ ...form, metric_formula: event.target.value })} /></label><label>单位<input value={form.metric_unit} onChange={(event) => setForm({ ...form, metric_unit: event.target.value })} /></label><label>适用工厂<input value={form.applicable_factories} placeholder="逗号分隔" onChange={(event) => setForm({ ...form, applicable_factories: event.target.value })} /></label><label>适用产品线<input value={form.applicable_product_lines} placeholder="逗号分隔" onChange={(event) => setForm({ ...form, applicable_product_lines: event.target.value })} /></label><label>生效日期<input type="date" value={form.effective_from} onChange={(event) => setForm({ ...form, effective_from: event.target.value })} /></label><div><button className="primary-button" disabled={saving}>{saving ? "保存中..." : "保存口径"}</button><button type="button" className="text-button" onClick={() => setOpen(false)}>取消</button></div></form>;
}

export function DocumentTaskList({ documents, knowledgeBaseId, organizationRole, onSource, onRetry, onCancel, onArchive, onDelete, onReplace, onMetadata }: Props) {
  const rows = documents.filter((document) => document.knowledge_base_id === knowledgeBaseId);
  const canManage = !!organizationRole && ["org_admin", "platform_admin"].includes(organizationRole);
  return <div className="knowledge-task-list">{rows.length ? rows.map((document) => <div className="knowledge-task-row" key={document.id}><span>{document.filename}{document.duplicate && <small className="export-error">重复文件，已复用现有版本</small>}</span><span className={`status-dot-label ${document.status}`}>{document.is_archived ? "archived" : document.status}</span><span className="document-meta">{document.category || "other"}{document.embedding_model ? ` · ${document.embedding_model} · ${document.embedding_dimension || "?"}d` : " · 未向量化"}{document.metric_name ? ` · 指标：${document.metric_name}` : ""}</span>{document.metric_definition && <small className="detail-hint">定义：{document.metric_definition}</small>}{document.metric_formula && <small className="detail-hint">公式：{document.metric_formula}{document.metric_unit ? `（${document.metric_unit}）` : ""}</small>}{document.error_message && <small className="export-error">{document.error_message}</small>}{document.status === "completed" && <button className="text-button" onClick={() => onSource(document)}>查看原文</button>}{document.ingestion_task_id && document.status === "failed" && <button className="text-button" onClick={() => onRetry(document.ingestion_task_id!)}>重试摄取</button>}{document.ingestion_task_id && ["queued", "processing"].includes(document.status) && <button className="text-button" onClick={() => onCancel(document.ingestion_task_id!)}>取消摄取</button>}{canManage && <><MetadataEditor document={document} onSave={(metadata) => onMetadata(document, metadata)} /><label className="text-button">替换上传<input type="file" accept=".pdf,.md,.markdown,.txt" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void onReplace(document, file); event.currentTarget.value = ""; }} /></label><button className="text-button" onClick={() => onArchive(document)}>{document.is_archived ? "恢复" : "归档"}</button>{!["queued", "processing"].includes(document.status) && <button className="text-button" onClick={() => onDelete(document)}>删除</button>}</>}</div>) : <p className="detail-hint">当前知识库还没有文档。</p>}</div>;
}
