import { DataView } from "../../components/DataView";
import type { KnowledgeBase, Report, ReportExport, Source } from "../../app/domain-types";
import { ReportExportStatus, type ExportItem } from "./ReportExportStatus";
import { ReportList } from "./ReportList";

export type ReportFilters = { title: string; status: string; createdBy: string; runId: string; createdFrom: string; createdTo: string };
type Props = { reports: Report[]; selectedReport: Report | null; exports: ReportExport[]; sources: Source[]; knowledgeBases: KnowledgeBase[]; filters: ReportFilters; setFilters: (filters: ReportFilters) => void; onOpen: (id: string) => void; onClose: () => void; onDownload: (id: string) => void; onRetryExport: (reportId: string, exportId: string) => void };

export function ReportsPage({ reports, selectedReport, exports, sources, knowledgeBases, filters, setFilters, onOpen, onClose, onDownload, onRetryExport }: Props) {
  const update = (patch: Partial<ReportFilters>) => setFilters({ ...filters, ...patch });
  return <DataView kicker="REPORTS / TRACEABLE OUTPUT" title="报告中心" copy="查看报告正文、证据引用和 PDF 导出状态。"><div className="report-filters"><input value={filters.title} onChange={(event) => update({ title: event.target.value })} placeholder="按标题筛选" aria-label="按报告标题筛选" /><select value={filters.status} onChange={(event) => update({ status: event.target.value })} aria-label="按报告状态筛选"><option value="">全部状态</option><option value="ready">已生成</option><option value="failed">失败</option></select><input value={filters.runId} onChange={(event) => update({ runId: event.target.value })} placeholder="按分析运行 ID" aria-label="按分析运行 ID 筛选" /><input value={filters.createdBy} onChange={(event) => update({ createdBy: event.target.value })} placeholder="按创建人 ID" aria-label="按创建人 ID 筛选" /><label>开始时间<input type="datetime-local" value={filters.createdFrom} onChange={(event) => update({ createdFrom: event.target.value })} aria-label="报告开始时间" /></label><label>结束时间<input type="datetime-local" value={filters.createdTo} onChange={(event) => update({ createdTo: event.target.value })} aria-label="报告结束时间" /></label></div><ReportList reports={reports} onOpen={onOpen} onDownload={onDownload} />{selectedReport && <section className="detail-panel report-detail"><div className="panel-heading"><div><p className="section-kicker">REPORT / TRACEABLE OUTPUT</p><h3>{selectedReport.title}</h3></div><button className="text-button" onClick={onClose}>关闭</button></div><pre className="markdown-preview">{selectedReport.markdown || "报告正文暂不可用"}</pre><div className="detail-meta"><span>分析状态：{selectedReport.analysis_status || "—"}</span><span>数据源：{sources.find((item) => item.id === selectedReport.data_source_id)?.name || selectedReport.data_source_id || "—"}</span><span>知识库：{knowledgeBases.find((item) => item.id === selectedReport.knowledge_base_id)?.name || selectedReport.knowledge_base_id || "—"}</span></div>{selectedReport.analysis_sql_draft && <details className="result-detail"><summary>SQL 草案</summary><pre className="sql-preview">{selectedReport.analysis_sql_draft}</pre></details>}{selectedReport.analysis_sql && <details className="result-detail"><summary>最终 SQL</summary><pre className="sql-preview">{selectedReport.analysis_sql}</pre></details>}<h4>引用（{selectedReport.citations?.length || 0}）</h4><div className="citation-list">{(selectedReport.citations || []).map((citation, index) => <p className="citation-item" key={index}>{String(citation.document_name || citation.document_id || "文档")} · {String(citation.location || "已引用")}</p>)}</div><ReportExportStatus items={exports as ExportItem[]} reportId={selectedReport.id} onRetry={onRetryExport} /></section>}</DataView>;
}
